spring:
  application:
    name: gatewayserver
  profiles:
    active: ${PROFILE:dev}
  config:
    import: "optional:configserver:${CONFIGSERVER_URI:http://configserver:8089}"

server:
  port: ${PORT:8072}

management:
  tracing:
    sampling:
      probability: 1.0
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
