spring:
  application:
    name: gatewayserver
  profiles:
    active: ${PROFILE:dev}
  config:
    import: "optional:configserver:${CONFIGSERVER_URI:http://configserver:8089}"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak:8080/realms/skate}
          jwk-set-uri: ${KEYCLOAK_JWK_URI:http://keycloak:8080/realms/skate/protocol/openid-connect/certs}

server:
  port: ${PORT:8072}

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
