spring:
  datasource:
    url: "jdbc:postgresql://database:5432/session_dev"
    username: "postgres"
    password: "postgres" #{cipher}a408581f1d4c56bd8a013a1a9a20867b1b0c4e324c36ea153558903212f88043

services:
  spot:
    url: http://spot-service-dev:8080
  skater:
    url: http://skater-service-dev:8081
