# Default Properties for skater-service
spring:
  application:
    name: skater-service
  jpa:
    hibernate:
      ddl-auto: "none"
    database: "POSTGRESQL"
    show-sql: true
    naming-strategy: "org.hibernate.cfg.ImprovedNamingStrategy"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
  datasource:
    driver-class-name: "org.postgresql.Driver"
    testWhileIdle: true
    validationQuery: "SELECT 1"

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      enabled: true
      show-details: always
      db:
        enabled: false
      diskspace:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

logging:
  level:
    root: INFO
    org.skate: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
