# Database Source Settings
spring.datasource.url=jdbc:postgresql://database:5432/spot_dev
spring.datasource.username=postgres
spring.datasource.password= # TODO: Add encrypted password for dev environment