# Default Properties for spot-service
spring:
  application:
    name: spot-service
  jpa:
    hibernate:
      ddl-auto: "none"
    database: "POSTGRESQL"
    show-sql: true
    naming-strategy: "org.hibernate.cfg.ImprovedNamingStrategy"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
  datasource:
    driver-class-name: "org.postgresql.Driver"
    testWhileIdle: true
    validationQuery: "SELECT 1"

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/

management:
  endpoints:
    enabled-by-default: false
    health:
      enabled: true
      show-details: "always"
      db:
        enabled: false
      diskspace:
        enabled: true