spring:
  datasource:
    url: "jdbc:postgresql://spot-database:5432/spot_dev"
    username: "postgres"
    password: "postgres" #{cipher}a408581f1d4c56bd8a013a1a9a20867b1b0c4e324c36ea153558903212f88043

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/