spring:
  application:
    name: config-server
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:native}
  cloud:
    config:
      server:
        native:
          search-locations: ${SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS:classpath:/config}

server:
  port: ${PORT:8089}

encrypt:
  key: ${ENCRYPT_KEY:oK5wCXS4nADchiI9WEXYPdJrqeNhuzxeTFSwf1qo5ic=}

management:
  endpoints:
    web:
      exposure:
        include: "*"