spring:
  application:
    name: skater-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  cloud:
    config:
      uri: http://configserver:8089
      fail-fast: false
      retry:
        max-attempts: 10
        initial-interval: 2000
